name: morning

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
jobs:
  send_message:
    runs-on: ubuntu-latest
    name: send morning to your girlfriend

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - uses: actions/checkout@v3
      - name: checkout
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: sender
        run: pip install -r ./requirements.txt && python ./main.py

    env:
      APP_ID: wxdb981250062f6ac3
      APP_SECRET: 8ea3d6c044c8ae12329d45586cb24df3
      KEY: 56928dd7fcf676b5c2a3c74f68fa8b8c
      TEMPLATE_ID: AtgaD2O5oW7FAnJZxt09IsN6az99Mx51u3G5gDcuqmQ

